# Site settings
title: dbuggen
author: "Aron Strandberg"
email: chefred@d.kth.se
description: >
  dbuggen är en en tidning som produceras av Redaqtionen på Datasektionen vid KTH i Stockholm
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dbu.gg" # the base hostname & protocol for your site
squareLogo: "https://scontent-ams3-1.xx.fbcdn.net/hphotos-xtp1/t31.0-8/12291669_909735382436061_4482356889120832467_o.jpg"
# Build settings
markdown: kramdown
# permalink: pretty
permalink: /:title
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# sass
sass:
  sass_dir: _sass
  style: :expanded

# dev options
port: 9000

# production options
gems: ['kramdown', 'yaml']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
